# Site settings
TZ: Europe/Kiev
title: Vazha Omanashvili - Software Developer
domain: vazha.me
url: http://vazha.me
repo: https://github.com/rainum/vazha.me

# Global data
author: Vazha Omanashvili
email: rainum.ua@gmail.com
description: >
  Vazha Omanashvili is a Ukraine based Software Developer who likes to develop an awesome stuff.

about_me: |
  ### Hey there!

  My name is Vazha Omanashvili. I'm a Software Developer from Ukraine.

  I work as an Engineering Manager at [SmartBear](https://smartbear.com), a company that builds software for Testing, Monitoring, and Developer Tools. I spent most of my time solving complex issues and mentoring. I've got a master's degree in computer science.

  I'm focused on JavaScript, TypeScript, and React. I'm interested in building and designing APIs, solving architecture issues, and functional programming. I specialize in messaging architectures, async/concurrent backends, and REST APIs.

  [Download my CV](https://drive.google.com/uc?export=download&id=1Csbg2PH-d5jK3KzxTGojt_Y-ED8P1vcp)

google_analytics_id: UA-7589447-3
twitter_username: vazhaom
github_username: rainum
linkedin_profile: https://www.linkedin.com/in/vazha
meta:
  - name: author
    content: Vazha Omanashvili

  - name: copyright
    content: Vazha Omanashvili

# Collections
collections:
  - projects

# Build settings
minify_html: true
markdown: kramdown
exclude:
  - README.md
  - .gitignore
  - autoprefixer.yml
  - Gemfile
  - Gemfile.lock

assets:
  compress:
    css: true
    js: true
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

plugins:
  - jekyll-assets
  - octopress-minify-html
